"""empty message

Revision ID: 39d5f54d8ed8
Revises: c3383d3ead3c
Create Date: 2023-01-19 00:47:43.890295

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39d5f54d8ed8"
down_revision = "c3383d3ead3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("articles")
    # ### end Alembic commands ###
