"""empty message

Revision ID: 7cc51f03449c
Revises: 78f7ba88a81c
Create Date: 2023-01-25 19:43:49.234335

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cc51f03449c"
down_revision = "78f7ba88a81c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.alter_column("author_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.alter_column("author_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
